### PR TITLE
Adds working disk image 

### PR DESCRIPTION
**Pull request by davidvossel**
There's still an issue with the ssh command failing from the manager, but the cluster actually forms (control plane node boots and worker joins) with these changes.

### CODE REVIEW

**Comment by davidvossel** [comment]
Ugh... I figured out the ssh issue. Fedora made a change to the crypto policies. For SSH to succeed, the image needs to be rebuilt with `update-crypto-policies --set LEGACY`.

**Comment by rmohr** [comment]
> Ugh... I figured out the ssh issue. Fedora made a change to the crypto policies. For SSH to succeed, the image needs to be rebuilt with `update-crypto-policies --set LEGACY`.

Does capik use too short rsa keys? Maybe only 1024?

**Review by rmohr — APPROVED** [review]
/lgtm
/approve

**Comment by rmohr** [comment]
> Do they use too short rsa keys? Maybe only 1024?

No 4096. :/

**Pull request merged**
